SELECT * FROM WATER_QUALITY.FEATURES.TRAINING_FEATURES;

SELECT * FROM WATER_QUALITY.FEATURES.VALIDATION_FEATURES;

SELECT * FROM WATER_QUALITY.RAW.WATER_QUALITY_TRAINING;

SELECT * FROM WATER_QUALITY.FEATURES.VALIDATION_FEATURES V
JOIN WATER_QUALITY.RAW.SUBMISSION_TEMPLATE S
ON S.LATITUDE = V.LATITUDE
AND S.LONGITUDE = V.LONGITUDE
AND S.SAMPLE_DATE = V.SAMPLE_DATE;