SELECT * FROM WATER_QUALITY.FEATURES.TRAINING_FEATURES;

SELECT * FROM WATER_QUALITY.FEATURES.VALIDATION_FEATURES;

SELECT * FROM WATER_QUALITY.RAW.WATER_QUALITY_TRAINING;

SELECT * FROM WATER_QUALITY.FEATURES.VALIDATION_FEATURES V
JOIN WATER_QUALITY.RAW.SUBMISSION_TEMPLATE S
ON S.LATITUDE = V.LATITUDE
AND S.LONGITUDE = V.LONGITUDE
AND S.SAMPLE_DATE = V.SAMPLE_DATE;

USE ROLE ACCOUNTADMIN;
USE DATABASE WATER_QUALITY;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DATA_CHALLENGE_EXTERNAL_ACCESS
  ALLOWED_NETWORK_RULES = (
    SNOWFLAKE_LEARNING_DB.PUBLIC.PYPI_NETWORK_RULE,
    SNOWFLAKE_LEARNING_DB.PUBLIC.PLANETARY_COMPUTER_NETWORK_RULE
  )
  ENABLED = TRUE;

