USE DATABASE WATER_QUALITY;

CREATE OR REPLACE TABLE ML_MODELS.MODEL_RUNS (
    MODEL_RUN_ID                  STRING        DEFAULT UUID_STRING(),
    TARGET_PARAMETER              STRING        NOT NULL,       
    MODEL_TYPE                    STRING        NOT NULL,               
    FEATURE_SET                   STRING        NOT NULL,                
    PARAMS                        VARIANT,                                
    MODEL_METRICS                 VARIANT,                               
    STATUS                        STRING        NOT NULL DEFAULT 'STARTED',
    STARTED_AT                    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ENDED_AT                      TIMESTAMP_NTZ,
    ERROR_MESSAGE                 STRING,
    GIT_SHA                       STRING,
    CREATED_AT                    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT                    TIMESTAMP_NTZ
);

CREATE OR REPLACE VIEW ML_MODELS.V_MODEL_RUNS_LATEST AS
SELECT *
FROM ML_MODELS.MODEL_RUNS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY TARGET_PARAMETER, MODEL_TYPE, FEATURE_SET
  ORDER BY STARTED_AT DESC
) = 1;

CREATE OR REPLACE VIEW ML_MODELS.V_TOP_MODEL_PER_TARGET AS
SELECT
  *,
  COALESCE(
    TRY_TO_DOUBLE(MODEL_METRICS:"test_r2")
  ) AS RANK_SCORE_R2
FROM ML_MODELS.MODEL_RUNS
WHERE STATUS = 'SUCCESS'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY TARGET_PARAMETER
  ORDER BY
    RANK_SCORE_R2 DESC NULLS LAST,
    ENDED_AT DESC NULLS LAST,
    STARTED_AT DESC
) = 1;